# Generated by Django 4.1.1 on 2022-09-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('specialization', models.CharField(max_length=50, verbose_name='Специализация')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('site', models.CharField(max_length=50, verbose_name='Сайт')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
            },
        ),
    ]
